"""Updated connection between notes and notebooks from o2m to m2m

Revision ID: bf95ace943b2
Revises: d3b384b5965f
Create Date: 2024-02-20 20:53:02.960185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf95ace943b2'
down_revision: Union[str, None] = 'd3b384b5965f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assotiation_note_notebook',
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ),
    sa.PrimaryKeyConstraint('notebook_id', 'note_id')
    )
    op.alter_column('notes', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('notes', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('notes_notebook_id_fkey', 'notes', type_='foreignkey')
    op.drop_column('notes', 'notebook_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('notebook_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('notes_notebook_id_fkey', 'notes', 'notebooks', ['notebook_id'], ['id'], ondelete='CASCADE')
    op.alter_column('notes', 'body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notes', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_table('assotiation_note_notebook')
    # ### end Alembic commands ###
